import { Store } from "./entities/loja.entity";

export const initialStores: Partial<Store>[] = [
  {
    storeName: "PDV Central",
    takeOutInStore: true,
    shippingTimeInDays: 1,
    latitude: "-23.550520",
    longitude: "-46.633308",
    address1: "Av. Paulista, 1000",
    city: "São Paulo",
    district: "Bela Vista",
    state: "SP",
    type: "PDV",
    country: "BR",
    postalCode: "01310-100",
    telephoneNumber: "(11) 9999-9999",
    emailAddress: "pdv.central@example.com",
  },
  {
    storeName: "LOJA Central",
    takeOutInStore: true,
    shippingTimeInDays: 1,
    latitude: "-23.550520",
    longitude: "-46.633308",
    address1: "Av. Paulista, 1000",
    city: "São Paulo",
    district: "Bela Vista",
    state: "SP",
    type: "LOJA",
    country: "BR",
    postalCode: "01310-100",
    telephoneNumber: "(11) 9999-9999",
    emailAddress: "loja.central@example.com",
  },
  {
    storeName: "PDV Recife",
    takeOutInStore: true,
    shippingTimeInDays: 2,
    latitude: "-8.0510932764335",
    longitude: "-34.901991630546",
    address1: "Rua Guilherme Pinto, 2000",
    city: "Recife",
    district: "Graças",
    state: "PE",
    type: "PDV",
    country: "BR",
    postalCode: "52011-210",
    telephoneNumber: "(81) 9999-9999",
    emailAddress: "loja.recife@example.com",
  },
];
